### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by arch-fan** [DrexHD/Vanish#4]
Mod is throwing this error

> Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[17:48:25] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.10
[17:48:26] [main/INFO]: Loading 63 mods:
        - antixray 1.2.6
        - brandblock 1.1.0
        - chunkpregen 0.3.3
        - clumps 9.0.0+11
        - com_electronwill_night-config_core 3.6.6 via servercore
        - com_electronwill_night-config_toml 3.6.6 via servercore
        - com_github_llamalad7_mixinextras 0.1.0 via servercore
        - com_moandjiezana_toml_toml4j 0.7.2 via antixray
        - com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
        - fabric-api 0.66.0+1.19.2
        - fabric-api-base 0.4.12+93d8cb8290 via fabric-api
        - fabric-api-lookup-api-v1 1.6.10+93d8cb8290 via fabric-api
        - fabric-biome-api-v1 9.0.18+c6af733c90 via fabric-api
        - fabric-block-api-v1 1.0.0+12bfe4ea90 via fabric-api
        - fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
        - fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
        - fabric-commands-v0 0.2.29+df3654b390 via fabric-api
        - fabric-containers-v0 0.1.35+df3654b390 via fabric-api
        - fabric-content-registries-v0 3.4.1+6064db2a90 via fabric-api
        - fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
        - fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
        - fabric-data-generation-api-v1 5.2.3+b598f4ac90 via fabric-api
        - fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
        - fabric-entity-events-v1 1.5.0+a1d87cb890 via fabric-api
        - fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
        - fabric-events-lifecycle-v0 0.2.29+df3654b390 via fabric-api
        - fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
        - fabric-item-api-v1 1.5.8+93d8cb8290 via fabric-api
        - fabric-item-groups-v0 0.3.33+70efcffe90 via fabric-api
        - fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via fabric-api
        - fabric-loot-api-v2 1.1.7+83a8659290 via fabric-api
        - fabric-loot-tables-v1 1.1.10+9e7660c690 via fabric-api
        - fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
        - fabric-mining-level-api-v1 2.1.18+33fbc73890 via fabric-api
        - fabric-networking-api-v1 1.2.5+c6af733c90 via fabric-api
        - fabric-networking-v0 0.3.22+df3654b390 via fabric-api
        - fabric-object-builder-api-v1 4.1.0+06e0e25190 via fabric-api
        - fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
        - fabric-permissions-api-v0 0.2-SNAPSHOT via melius-vanish
        - fabric-registry-sync-v0 0.9.26+c6af733c90 via fabric-api
        - fabric-rendering-data-attachment-v1 0.3.16+12bfe4ea90 via fabric-api
        - fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
        - fabric-resource-conditions-api-v1 2.1.0+aae9039d90 via fabric-api
        - fabric-resource-loader-v0 0.7.3+3e1ba48e90 via fabric-api
        - fabric-screen-handler-api-v1 1.3.1+1cc24b1b90 via fabric-api
        - fabric-transfer-api-v1 2.1.1+93d8cb8290 via fabric-api
        - fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
        - fabricloader 0.14.10
        - fastfurnace 1.19.2-5
        - java 17
        - krypton 0.2.1
        - lithium 0.10.2
        - me_lucko_spark-api 0.1-SNAPSHOT via servercore
        - melius-vanish 1.1.0
        - minecraft 1.19.2
        - packet_tweaker 0.3.0+1.18.2 via server_translations_api
        - placeholder-api 2.0.0-pre.1+1.19.2 via servercore
        - player-data-api 0.2.1+1.19 via melius-vanish
        - server_translations_api 1.4.17+1.19.2 via melius-vanish
        - servercore 1.3.3-1.19.2
        - sgui 1.1.4+1.19.1 via simple_trade_mod
        - simple_trade_mod 0.1.0+MC1.19.2
        - starlight 1.1.1+fabric.ae22326
[17:48:26] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/hdd-data/minecraft/server1/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[17:48:26] [main/INFO]: Compatibility level set to JAVA_16
[17:48:26] [main/INFO]: Compatibility level set to JAVA_17
[17:48:27] [main/WARN]: Reference map 'fabric-chunkpregen-refmap.json' for chunkpregen.mixins.json could not be read. If this is a development environment you can ignore this message
[17:48:27] [main/INFO]: Loaded configuration file for Lithium: 105 options available, 2 override(s) found
[17:48:27] [main/INFO]: [ServerCore] Loading...
[17:48:30] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[17:48:31] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[17:48:32] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'melius-vanish'!
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.10.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [server.jar:0.10.2]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'melius-vanish'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.10.jar:?]
        ... 4 more
Caused by: java.lang.LinkageError: loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3c09711b attempted duplicate class definition for com.llamalad7.mixinextras.MixinExtrasBootstrap. (com.llamalad7.mixinextras.MixinExtrasBootstrap is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3c09711b, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @7946e1f4)
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.10.jar:?]
        ... 4 more

**Comment by DrexHD** [comment]
This issue is similar / caused by the same issue as #3. Try using this version of [github actions servercore](https://github.com/Wesley1808/ServerCore/actions/runs/3387842162), which should fix this issue!
