### ISSUE TITLE
vanish-1.5.7+1.21.1.jar crash report

### ISSUE THREAD

**Issue by MarkHarrisMedia** [DrexHD/Vanish#52]
My server has crashed twice in the past week with this same crash report, please help me understand

![image](https://github.com/user-attachments/assets/7a2a7bf7-691b-4a3b-9031-997bd2cfe9e3)

[23:42:20 ERROR] [Server thread]: [MinecraftServer] Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1025) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:299) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:912) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.google.gson.JsonParseException: Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]
        at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
        at net.kyori.adventure.platform.fabric.impl.NonWrappingComponentSerializer.deserialize(NonWrappingComponentSerializer.java:66) ~[adventure-platform-fabric-5.14.0-8212e244c451835.jar:?]
        at net.minecraft.network.chat.Component.asComponent(Component.java:544) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.sendSystemMessage(DedicatedServer.java:1253) ~[?:?]
        at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:796) ~[?:?]
        at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:792) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.mixinextras$bridge$method_43514$320(ServerPlayer.java) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.wrapOperation$cio000$melius-vanish$vanish_hideDeathMessage(ServerPlayer.java:12163) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:710) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1252) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:977) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:811) ~[?:?]
        at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1502) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:151) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:144) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:65) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:112) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:103) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:794) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:2778) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:572) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44) ~[?:?]
        at net.minecraft.world.entity.monster.AbstractSkeleton.aiStep(AbstractSkeleton.java:125) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2507) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:372) ~[?:?]
        at net.minecraft.server.level.ServerLevel.mixinextras$bridge$method_5773$228(ServerLevel.java) ~[?:?]
        at net.minecraft.server.level.ServerLevel.wrapOperation$deg000$puzzleslib$tickNonPassenger(ServerLevel.java:11297) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:770) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:498) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:408) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:372) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1021) ~[server-intermediary.jar:?]
        ... 5 more
[23:42:20 ERROR] [Server thread]: [MinecraftServer] This crash report has been saved to: /home/container/crash-reports/crash-2024-10-10_23.42.20-server.txt
[23:42:26 INFO] [Server thread]: [BlueMap] BlueMap unloaded!
[23:42:26 INFO] [Server thread]: [geyser] Shutting down Geyser.

**Comment by DrexHD** [comment]
This is not an issue caused by vanish. This likely happens when a vanished player is killed by someone with an enchanted item. Are you using any chat mods that could bundle kyori_adventure? Can you sent all of your logs?
